###

GET http://0.0.0.0:3000 HTTP/1.1

###

GET http://0.0.0.0:3000/api/1 HTTP/1.1

### Query User

GET http://0.0.0.0:3000/api/users?page_size=100 HTTP/1.1

### Create User

POST http://0.0.0.0:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "王五",
    "gender": "male",
    "account": "wang",
    "password": "123456",
    "mobile_phone": "18361631783",
    "birthday": "2025-06-11"
}

### Update User

@user = 01986afed7f97f31bb87577ec490e14a

PUT http://0.0.0.0:3000/api/users/{{user}} HTTP/1.1
Content-Type: application/json

{
    "name": "李四",
    "gender": "male",
    "account": "wang",
    "password": "123456",
    "mobile_phone": "18361631781",
    "birthday": "2025-06-11"
}

### Delete User


DELETE http://0.0.0.0:3000/api/users/{{user}} HTTP/1.1

###